export const playlists = [
  {
    id: 1,
    name: "Top Nhạc Trẻ Hot",
    description: "Những bản nhạc trẻ đang được nghe nhiều nhất hiện nay",
    coverImage:
      "https://image-cdn.nct.vn/singer/avatar/2025/09/22/H/e/e/3/1758508420233_300.jpg",
    songs: [
      {
        id: 101,
        title: "Kho Báu",
        artist: "(S)TRONG & Rhymastic",
        image: "https://example.com/song_kho_bau.jpg",
        audio: "https://example.com/audio_kho_bau.mp3",
        duration: "03:16",
      },
      {
        id: 102,
        title: "Mất Kết Nối",
        artist: "Dương Domic",
        image: "https://example.com/song_mat_ket_noi.jpg",
        audio: "https://example.com/audio_mat_ket_noi.mp3",
        duration: "03:27",
      },
      {
        id: 103,
        title: "Sau Cơn Suy",
        artist: "RHYDER",
        image: "https://example.com/song_sau_con_suy.jpg",
        audio: "https://example.com/audio_sau_con_suy.mp3",
        duration: "03:13",
      },
      {
        id: 104,
        title: "Không Buông",
        artist: "Hngle & Ari",
        image: "https://example.com/song_khong_buong.jpg",
        audio: "https://example.com/audio_khong_buong.mp3",
        duration: "02:54",
      },
      {
        id: 105,
        title: "Người Đầu Tiên",
        artist: "EM XINH “SAY HI” & Juky San",
        image: "https://example.com/song_nguoi_dau_tien.jpg",
        audio: "https://example.com/audio_nguoi_dau_tien.mp3",
        duration: "03:52",
      },
      {
        id: 106,
        title: "Âm Thầm Bên Em",
        artist: "Sơn Tùng M-TP",
        image: "https://example.com/song_am_tham_ben_em.jpg",
        audio: "https://example.com/audio_am_tham_ben_em.mp3",
        duration: "04:51",
      },
    ],
  },
  {
    id: 2,
    name: "Ballad Nhẹ Nhàng",
    description: "Những bản ballad nhẹ nhàng và da diết",
    coverImage: "https://example.com/cover_ballad_nhe.jpg",
    songs: [
      {
        id: 201,
        title: "Kho Báu",
        artist: "(S)TRONG & Rhymastic",
        image: "https://example.com/song_kho_bau.jpg",
        audio: "https://example.com/audio_kho_bau.mp3",
        duration: "03:16",
      },
      {
        id: 202,
        title: "Ngày Này Năm Ấy",
        artist: "Việt Anh",
        image: "https://example.com/song_ngay_nay_nam_ay.jpg",
        audio: "https://example.com/audio_ngay_nay_nam_ay.mp3",
        duration: "03:59",
      },
      {
        id: 203,
        title: "Anh Đã Không Biết Cách Yêu Em",
        artist: "Quang Đăng Trần",
        image: "https://example.com/song_anh_da_khong.jpg",
        audio: "https://example.com/audio_anh_da_khong.mp3",
        duration: "04:05",
      },
      {
        id: 204,
        title: "Khóc Cùng Em",
        artist: "Ai Ai Là Anh",
        image: "https://example.com/song_khoc_cung_em.jpg",
        audio: "https://example.com/audio_khoc_cung_em.mp3",
        duration: "04:10",
      },
      {
        id: 205,
        title: "Gửi Người Yêu Cũ",
        artist: "Hồ Ngọc Hà",
        image: "https://example.com/song_gui_nguoi_yeu_cu.jpg",
        audio: "https://example.com/audio_gui_nguoi_yeu_cu.mp3",
        duration: "04:55",
      },
      {
        id: 206,
        title: "Như Phút Ban Đầu",
        artist: "Noo Phước Thịnh",
        image: "https://example.com/song_nhu_phut_ban_dau.jpg",
        audio: "https://example.com/audio_nhu_phut_ban_dau.mp3",
        duration: "03:45",
      },
    ],
  },
  {
    id: 3,
    name: "TikTok Trend Việt",
    description: "Các bài hát đang viral trên TikTok Việt Nam",
    coverImage: "https://example.com/cover_tiktok_trend.jpg",
    songs: [
      {
        id: 301,
        title: "See Tình",
        artist: "Hoàng Thùy Linh",
        image: "https://example.com/song_see_tinh.jpg",
        audio: "https://example.com/audio_see_tinh.mp3",
        duration: "03:23",
      },
      {
        id: 302,
        title: "Bắc Bling",
        artist: "Hòa Minzy, Xuân Hinh & Tuấn Cry",
        image: "https://example.com/song_bac_bling.jpg",
        audio: "https://example.com/audio_bac_bling.mp3",
        duration: "03:50",
      },
      {
        id: 303,
        title: "Sự Nghiệp Chướng",
        artist: "Pháo",
        image: "https://example.com/song_su_nghiep_chuong.jpg",
        audio: "https://example.com/audio_su_nghiep_chuong.mp3",
        duration: "03:58",
      },
      {
        id: 304,
        title: "Ai Hom Nay",
        artist: "Pháo, Masew",
        image: "https://example.com/song_ai_hom_nay.jpg",
        audio: "https://example.com/audio_ai_hom_nay.mp3",
        duration: "03:35",
      },
      {
        id: 305,
        title: "Tình Yêu Màu Hồng",
        artist: "Hồ Văn Quý & Xám",
        image: "https://example.com/song_tinh_yeu_mau_hong.jpg",
        audio: "https://example.com/audio_tinh_yeu_mau_hong.mp3",
        duration: "03:45",
      },
      {
        id: 306,
        title: "Hai Phút Hơn",
        artist: "Pháo & Masew",
        image: "https://example.com/song_hai_phut_hon.jpg",
        audio: "https://example.com/audio_hai_phut_hon.mp3",
        duration: "02:34",
      },
    ],
  },
  {
    id: 4,
    name: "Pop Quốc Tế & Việt",
    description: "Kết hợp những bản nhạc Pop quốc tế và Vpop được yêu thích",
    coverImage: "https://example.com/cover_pop_mix.jpg",
    songs: [
      {
        id: 401,
        title: "Bóng Phù Hoa",
        artist: "Phương Mỹ Chi & DTAP",
        image: "https://example.com/song_bong_phu_hoa.jpg",
        audio: "https://example.com/audio_bong_phu_hoa.mp3",
        duration: "04:10",
      },
      {
        id: 402,
        title: "Phép Màu",
        artist: "MAYDAYs & Minh Tốc & Lam",
        image: "https://example.com/song_phep_mau.jpg",
        audio: "https://example.com/audio_phep_mau.mp3",
        duration: "03:50",
      },
      {
        id: 403,
        title: "Kho Báu",
        artist: "(S)TRONG & Rhymastic",
        image: "https://example.com/song_kho_bau.jpg",
        audio: "https://example.com/audio_kho_bau.mp3",
        duration: "03:16",
      },
      {
        id: 404,
        title: "See Tình",
        artist: "Hoàng Thùy Linh",
        image: "https://example.com/song_see_tinh.jpg",
        audio: "https://example.com/audio_see_tinh.mp3",
        duration: "03:23",
      },
      {
        id: 405,
        title: "Âm Thầm Bên Em",
        artist: "Sơn Tùng M-TP",
        image: "https://example.com/song_am_tham_ben_em.jpg",
        audio: "https://example.com/audio_am_tham_ben_em.mp3",
        duration: "04:51",
      },
      {
        id: 406,
        title: "Một bước yêu vạn dặm đau",
        artist: "Mr. Siro",
        image: "https://example.com/song_mot_buoc_yeu.jpg",
        audio: "https://example.com/audio_mot_buoc_yeu.mp3",
        duration: "04:30",
      },
    ],
  },
  {
    id: 5,
    name: "Dance / Remix Sôi Động",
    description: "Những bản dance / remix khiến bạn muốn nhảy ngay",
    coverImage: "https://example.com/cover_remix.jpg",
    songs: [
      {
        id: 501,
        title: "Nhạc Remix TikTok Triệu View",
        artist: "Various Artists",
        image: "https://example.com/song_remix1.jpg",
        audio: "https://example.com/audio_remix1.mp3",
        duration: "05:00",
      },
      {
        id: 502,
        title: "All Eyes On Us",
        artist: "Various Artists",
        image: "https://example.com/song_all_eyes.jpg",
        audio: "https://example.com/audio_all_eyes.mp3",
        duration: "03:40",
      },
      {
        id: 503,
        title: "Cho Em Đi",
        artist: "Various Artists",
        image: "https://example.com/song_cho_em_di.jpg",
        audio: "https://example.com/audio_cho_em_di.mp3",
        duration: "03:20",
      },
      {
        id: 504,
        title: "Mất Kết Nối",
        artist: "Dương Domic",
        image: "https://example.com/song_mat_ket_noi.jpg",
        audio: "https://example.com/audio_mat_ket_noi.mp3",
        duration: "03:27",
      },
      {
        id: 505,
        title: "Phép Màu",
        artist: "MAYDAYs & Minh Tốc & Lam",
        image: "https://example.com/song_phep_mau.jpg",
        audio: "https://example.com/audio_phep_mau.mp3",
        duration: "03:50",
      },
      {
        id: 506,
        title: "Sai Cách Yêu",
        artist: "Vũ.",
        image: "https://example.com/song_sai_cach_yeu.jpg",
        audio: "https://example.com/audio_sai_cach_yeu.mp3",
        duration: "04:10",
      },
    ],
  },
  {
    id: 6,
    name: "Ballad Buồn Tâm Trạng",
    description: "Những bản ballad sâu lắng để tâm hồn thư giãn",
    coverImage: "https://example.com/cover_ballad_buon.jpg",
    songs: [
      {
        id: 601,
        title: "Cứ Đổ Tại Cơn Mưa",
        artist: "EM XINH “SAY HI” ft. Phương Ly",
        image: "https://example.com/song_cu_do_tai_con_mua.jpg",
        audio: "https://example.com/audio_cu_do_tai_con_mua.mp3",
        duration: "04:14",
      },
      {
        id: 602,
        title: "Nơi Này Có Anh",
        artist: "Sơn Tùng M-TP",
        image: "https://example.com/song_noi_nay_co_anh.jpg",
        audio: "https://example.com/audio_noi_nay_co_anh.mp3",
        duration: "04:20",
      },
      {
        id: 603,
        title: "Giờ Thì",
        artist: "buitruonglinh",
        image: "https://example.com/song_gio_thi.jpg",
        audio: "https://example.com/audio_gio_thi.mp3",
        duration: "03:54",
      },
      {
        id: 604,
        title: "Anh Vui",
        artist: "Phạm Kỳ",
        image: "https://example.com/song_anh_vui.jpg",
        audio: "https://example.com/audio_anh_vui.mp3",
        duration: "03:17",
      },
      {
        id: 605,
        title: "Khóc Cùng Em",
        artist: "Ai Ai Là Anh",
        image: "https://example.com/song_khoc_cung_em.jpg",
        audio: "https://example.com/audio_khoc_cung_em.mp3",
        duration: "04:10",
      },
      {
        id: 606,
        title: "Ngày Này Năm Ấy",
        artist: "Việt Anh",
        image: "https://example.com/song_ngay_nay_nam_ay.jpg",
        audio: "https://example.com/audio_ngay_nay_nam_ay.mp3",
        duration: "03:59",
      },
    ],
  },
  {
    id: 7,
    name: "V-Pop Trữ Tình / Tình Cảm",
    description: "Những ca khúc tình cảm sâu lắng của V-Pop",
    coverImage: "https://example.com/cover_vpop_trutinh.jpg",
    songs: [
      {
        id: 701,
        title: "Buông Đôi Tay Nhau Ra",
        artist: "Sơn Tùng M-TP",
        image: "https://example.com/song_buong_doi_tay.jpg",
        audio: "https://example.com/audio_buong_doi_tay.mp3",
        duration: "03:46",
      },
      {
        id: 702,
        title: "Âm Thầm Bên Em",
        artist: "Sơn Tùng M-TP",
        image: "https://example.com/song_am_tham_ben_em.jpg",
        audio: "https://example.com/audio_am_tham_ben_em.mp3",
        duration: "04:51",
      },
      {
        id: 703,
        title: "Gửi Người Yêu Cũ",
        artist: "Hồ Ngọc Hà",
        image: "https://example.com/song_gui_nguoi_yeu_cu.jpg",
        audio: "https://example.com/audio_gui_nguoi_yeu_cu.mp3",
        duration: "04:55",
      },
      {
        id: 704,
        title: "Ngàn Năm Ánh Sáng",
        artist: "Đặng Vĩnh Thịnh & BMZ",
        image: "https://example.com/song_ngan_nam_anh_sang.jpg",
        audio: "https://example.com/audio_ngan_nam_anh_sang.mp3",
        duration: "03:34",
      },
      {
        id: 705,
        title: "Nắng Dưới Chân Mây",
        artist: "Nguyễn Hữu Kha",
        image: "https://example.com/song_nang_duoi_chan_may.jpg",
        audio: "https://example.com/audio_nang_duoi_chan_may.mp3",
        duration: "03:39",
      },
      {
        id: 706,
        title: "Đóa Phù Đung Cuối Cùng",
        artist: "ANH TRAI “SAY HI” & Đức Phúc",
        image: "https://example.com/song_doa_phu_dung.jpg",
        audio: "https://example.com/audio_doa_phu_dung.mp3",
        duration: "05:27",
      },
    ],
  },
  {
    id: 8,
    name: "Lofi / Indie Chill Việt",
    description: "Những giai điệu indie / chill nhẹ nhàng thư giãn",
    coverImage: "https://example.com/cover_lofi_chill.jpg",
    songs: [
      {
        id: 801,
        title: "Sai Cách Yêu",
        artist: "Vũ.",
        image: "https://example.com/song_sai_cach_yeu.jpg",
        audio: "https://example.com/audio_sai_cach_yeu.mp3",
        duration: "04:10",
      },
      {
        id: 802,
        title: "Mười Năm Tình Cũ",
        artist: "Đàm Vĩnh Hưng",
        image: "https://example.com/song_muoi_nam_tinh_cu.jpg",
        audio: "https://example.com/audio_muoi_nam_tinh_cu.mp3",
        duration: "04:45",
      },
      {
        id: 803,
        title: "Cánh Hồng Phai",
        artist: "Hòa Minzy",
        image: "https://example.com/song_canh_hong_phai.jpg",
        audio: "https://example.com/audio_canh_hong_phai.mp3",
        duration: "03:50",
      },
      {
        id: 804,
        title: "Chờ Người Nơi Ấy",
        artist: "Ưng Hoàng Phúc",
        image: "https://example.com/song_cho_nguoi_noi_ay.jpg",
        audio: "https://example.com/audio_cho_nguoi_noi_ay.mp3",
        duration: "04:25",
      },
      {
        id: 805,
        title: "Yêu Em Từ Cái Nhìn Đầu Tiên",
        artist: "Noo Phước Thịnh",
        image: "https://example.com/song_yeu_em_tu_cai_nhin_dau_tien.jpg",
        audio: "https://example.com/audio_yeu_em_tu_cai_nhin_dau_tien.mp3",
        duration: "03:30",
      },
      {
        id: 806,
        title: "Lỡ hẹn với cô đơn",
        artist: "Will & Kaity",
        image: "https://example.com/song_lo_hem_co_don.jpg",
        audio: "https://example.com/audio_lo_hem_co_don.mp3",
        duration: "03:40",
      },
    ],
  },
  {
    id: 9,
    name: "Rap / Hip Hop Việt",
    description: "Rap và hip hop Việt Nam đang được nghe nhiều",
    coverImage: "https://example.com/cover_rap_viet.jpg",
    songs: [
      {
        id: 901,
        title: "Mất Kết Nối",
        artist: "Dương Domic",
        image: "https://example.com/song_mat_ket_noi.jpg",
        audio: "https://example.com/audio_mat_ket_noi.mp3",
        duration: "03:27",
      },
      {
        id: 902,
        title: "Sai Cách Yêu",
        artist: "Vũ.",
        image: "https://example.com/song_sai_cach_yeu.jpg",
        audio: "https://example.com/audio_sai_cach_yeu.mp3",
        duration: "04:10",
      },
      {
        id: 903,
        title: "All Eyes On Us",
        artist: "Various Artists",
        image: "https://example.com/song_all_eyes.jpg",
        audio: "https://example.com/audio_all_eyes.mp3",
        duration: "03:40",
      },
      {
        id: 904,
        title: "Ai Hom Nay",
        artist: "Pháo, Masew",
        image: "https://example.com/song_ai_hom_nay.jpg",
        audio: "https://example.com/audio_ai_hom_nay.mp3",
        duration: "03:35",
      },
      {
        id: 905,
        title: "Kho Báu",
        artist: "(S)TRONG & Rhymastic",
        image: "https://example.com/song_kho_bau.jpg",
        audio: "https://example.com/audio_kho_bau.mp3",
        duration: "03:16",
      },
      {
        id: 906,
        title: "Bắc Bling",
        artist: "Hòa Minzy, Xuân Hinh & Tuấn Cry",
        image: "https://example.com/song_bac_bling.jpg",
        audio: "https://example.com/audio_bac_bling.mp3",
        duration: "03:50",
      },
    ],
  },
  {
    id: 10,
    name: "Việt Nam Hot 100",
    description: "Những bài Việt Nam nằm trong Top 100 Billboard / Hot Chart",
    coverImage: "https://example.com/cover_hot100.jpg",
    songs: [
      {
        id: 1001,
        title: "Phép Màu",
        artist: "MAYDAYs & Minh Tốc & Lam",
        image: "https://example.com/song_phep_mau.jpg",
        audio: "https://example.com/audio_phep_mau.mp3",
        duration: "03:50",
      },
      {
        id: 1002,
        title: "Còn Gì Đẹp Hơn",
        artist: "Nguyễn Hùng",
        image: "https://example.com/song_con_gi_dep_hon.jpg",
        audio: "https://example.com/audio_con_gi_dep_hon.mp3",
        duration: "03:45",
      },
      {
        id: 1003,
        title: "Kho Báu",
        artist: "(S)TRONG & Rhymastic",
        image: "https://example.com/song_kho_bau.jpg",
        audio: "https://example.com/audio_kho_bau.mp3",
        duration: "03:16",
      },
      {
        id: 1004,
        title: "Bóng Phù Hoa",
        artist: "Phương Mỹ Chi & DTAP",
        image: "https://example.com/song_bong_phu_hoa.jpg",
        audio: "https://example.com/audio_bong_phu_hoa.mp3",
        duration: "04:10",
      },
      {
        id: 1005,
        title: "Âm Thầm Bên Em",
        artist: "Sơn Tùng M-TP",
        image: "https://example.com/song_am_tham_ben_em.jpg",
        audio: "https://example.com/audio_am_tham_ben_em.mp3",
        duration: "04:51",
      },
      {
        id: 1006,
        title: "Mất Kết Nối",
        artist: "Dương Domic",
        image: "https://example.com/song_mat_ket_noi.jpg",
        audio: "https://example.com/audio_mat_ket_noi.mp3",
        duration: "03:27",
      },
    ],
  },
];
